import streamlit as st

# Set page configuration
st.set_page_config(
    page_title="Noor Al-Logha",
    page_icon="🌙",
    layout="wide",
)

# Application Header
st.title("🌙 Noor Al-Logha (نور اللغة)")
st.caption("Embark on your journey to master Arabic—designed for beginners.")

st.divider()

# Project Overview
col_left, col_right = st.columns([2, 1])

with col_left:
    st.header("Why Learn Arabic?")
    st.write("""
    Learning a new language is one of the best ways to keep the mind sharp. 
    **Noor Al-Logha** uses AI to guide you through the beautiful Arabic language at your own pace.
    """)
    
    st.subheader("Our Approach")
    st.write("- **No Pressure**: Learn at your own pace.")
    st.write("- **Voice First**: Interactive guidance.")
    st.write("- **Accessible**: Simple and clear interface.")

with col_right:
    st.subheader("Word of the Day")
    st.info("مرحباً \n\n (Marhaban - Welcome)")

# Core Features
st.divider()
st.header("Learning Modules")

f1, f2, f3 = st.columns(3)

with f1:
    st.subheader("🅰️ The Alphabet")
    st.write("Master the script with visual guides and audio pronunciation.")

with f2:
    st.subheader("💬 Daily Phrases")
    st.write("Learn essential greetings and everyday sentences.")

with f3:
    st.subheader("📖 AI Stories")
    st.write("Short, cultural stories generated by AI for context.")

# Hackathon Info
st.write("---")
st.info("""
**Hackathon Project**: Arabic Learning for Beginners (Seniors Focus)
**Key Tech**: Streamlit, Groq API (for conversation), Google TTS (for Arabic audio).
**Goal**: Reduce cognitive decline through language learning and foster cultural appreciation.
""")

# Call to Action
st.write("---")
col_btn1, col_btn2, col_btn3 = st.columns(3)
with col_btn1:
    if st.button("🔍 Level Detector"):
        st.switch_page("pages/1_Level_Detector.py")

with col_btn2:
    if st.button("📖 Word Translator"):
        st.switch_page("pages/2_Word_Translator.py")

with col_btn3:
    if st.button("🚀 Start Learning"):
        st.balloons()
        st.success("أهلاً بك! Let's begin!")
